# Pandas

In [1]:
import pandas as pd
import numpy as np

### 1. Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [2]:
nums = [num for num in range(11)]

column = pd.Series(nums)

column

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

### 2. Write a Python program to convert a Panda module Series to Python list and it's type.

In [3]:
nums_list = column.astype(float).to_list()

nums_list

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

### 3. Write a Python program to add, subtract, multiple and divide two Pandas Series.
#### Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [4]:
series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series([1, 3, 5, 7, 9])

print("Addition: ")
print(series1 + series2)

print("Substraction: ")
print(series1 - series2)

print("Multiplication: ")
print(series2 * series1)

print("Division :")
print(series2 / series1)

Addition:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Substraction:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiplication:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Division :
0    0.500000
1    0.750000
2    0.833333
3    0.875000
4    0.900000
dtype: float64

#### 4. Write a Python program to get the powers of an array values element-wise.

- Note: First array elements raised to powers from second array
- Expected Output:
- Original array [0 1 2 3 4 5 6]

- First array elements raised to powers from second array, element-wise:
[ 0 1 8 27 64 125 216]

In [5]:
series1 ** series2

0             2
1            64
2          7776
3       2097152
4    1000000000
dtype: int64

### 5. Write a Python program to create and display a DataFrame from a specified dictionary data which has the index labels.

In [6]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


df = pd.DataFrame(exam_data,index=labels)

df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

### 6. Write a Python program to display a summary of the basic information about a specified Data Frame and its data.

In [7]:
df.info()

<class 'pandas.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     str
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64
 3   qualify   10 non-null     str
dtypes: float64(1), int64(1), str(2)
memory usage: 400.0+ bytes

### 7. Write a Python program to get the first 3 rows of a given DataFrame.

In [8]:
df[:3]

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

### 8. Write a Python program to select the 'name' and 'score' columns from the following DataFrame.

In [9]:
df[['name','score']]

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

### 9. Write a Python program to select the specified columns and rows from a given dataframe.
#### Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.

In [10]:
df.iloc[[1,3,5,6]][['name','score']]

      name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5

### 10. Write a Python program to select the rows where the number of attempts in the examination is greater than 2.

In [11]:
df[df['attempts'] > 2]

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

### 11. Write a Python program to count the number of rows and columns of a DataFrame

In [12]:
rows, columns = df.shape

print(f"Number of Rows = {rows}")
print(f"Number of columns = {columns}")

Number of Rows = 10
Number of columns = 4

### 12. Write a Python program to select the rows where the score is missing, i.e. is NaN.

In [13]:
df[df['score'].isnull()]

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

### 13. Write a Python program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.

In [14]:
df[(df['attempts'] < 2) & (df['score'] > 15)]

    name  score  attempts qualify
j  Jonas   19.0         1     yes

### 14. Write a Python program to change the score in row 'd' to 11.5.

In [15]:
df.loc['d','score'] = 11.5
df.loc['d']

name        James
score        11.5
attempts        3
qualify        no
Name: d, dtype: object

### 15. Write a Python program to calculate the sum of the examination attempts by the students.

In [16]:
print(df['attempts'].sum())

19

### 16. Write a Python program to calculate the mean score for each different student in DataFrame

In [17]:
result = df.groupby('name')['score'].mean()
result = result.reset_index()
result.rename(columns={'score': 'mean_score'}, inplace=True)
print(result)

        name  mean_score
0  Anastasia        12.5
1       Dima         9.0
2      Emily         9.0
3      James        11.5
4      Jonas        19.0
5  Katherine        16.5
6      Kevin         8.0
7      Laura         NaN
8    Matthew        14.5
9    Michael        20.0

### 17. Write a Python program to append a new row 'k' to data frame with given values for each column. Now delete the new row and return the original DataFrame.

In [18]:
df.loc['k'] = ['john', 11, 2, 'yes']

print(df.loc['k'])

df.drop(index='k', inplace=True)

name        john
score       11.0
attempts       2
qualify      yes
Name: k, dtype: object

In [19]:
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

### 18. Write a Python program to sort the DataFrame first by 'name' in descending order, then by 'score' in ascending order.

In [20]:
df.sort_values('name')

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
e      Emily    9.0         2      no
d      James   11.5         3      no
j      Jonas   19.0         1     yes
c  Katherine   16.5         2     yes
i      Kevin    8.0         2      no
h      Laura    NaN         1      no
g    Matthew   14.5         1     yes
f    Michael   20.0         3     yes

In [21]:
df.sort_values('score', ascending=False)

        name  score  attempts qualify
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes
c  Katherine   16.5         2     yes
g    Matthew   14.5         1     yes
a  Anastasia   12.5         1     yes
d      James   11.5         3      no
b       Dima    9.0         3      no
e      Emily    9.0         2      no
i      Kevin    8.0         2      no
h      Laura    NaN         1      no

### 19. Write a Python program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.

In [24]:
df['qualify'] = df['qualify'].apply(lambda value: value == 'yes')

In [25]:
df

        name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James   11.5         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True

### 20. Write a Python program to delete the 'attempts' column from the DataFrame.

In [27]:
df.drop(columns='attempts', inplace=True)

In [28]:
df

        name  score  qualify
a  Anastasia   12.5     True
b       Dima    9.0    False
c  Katherine   16.5     True
d      James   11.5    False
e      Emily    9.0    False
f    Michael   20.0     True
g    Matthew   14.5     True
h      Laura    NaN    False
i      Kevin    8.0    False
j      Jonas   19.0     True

### 21. Write a Python program to insert a new column in existing DataFrame

In [29]:
df['attempts'] = [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
df

        name  score  qualify  attempts
a  Anastasia   12.5     True         1
b       Dima    9.0    False         3
c  Katherine   16.5     True         2
d      James   11.5    False         3
e      Emily    9.0    False         2
f    Michael   20.0     True         3
g    Matthew   14.5     True         1
h      Laura    NaN    False         1
i      Kevin    8.0    False         2
j      Jonas   19.0     True         1

### 22. Write a Python program to iterate over rows in a DataFrame.

In [40]:
for row in df.itertuples():
    print(row)

Pandas(Index='a', name='Anastasia', score=12.5, qualify=True, attempts=1)
Pandas(Index='b', name='Dima', score=9.0, qualify=False, attempts=3)
Pandas(Index='c', name='Katherine', score=16.5, qualify=True, attempts=2)
Pandas(Index='d', name='James', score=11.5, qualify=False, attempts=3)
Pandas(Index='e', name='Emily', score=9.0, qualify=False, attempts=2)
Pandas(Index='f', name='Michael', score=20.0, qualify=True, attempts=3)
Pandas(Index='g', name='Matthew', score=14.5, qualify=True, attempts=1)
Pandas(Index='h', name='Laura', score=nan, qualify=False, attempts=1)
Pandas(Index='i', name='Kevin', score=8.0, qualify=False, attempts=2)
Pandas(Index='j', name='Jonas', score=19.0, qualify=True, attempts=1)

### 23. Write a Python program to get list from DataFrame column headers.

In [44]:
print(df.columns)

Index(['name', 'score', 'qualify', 'attempts'], dtype='str')